# Objectif PFE : Gestion sécurisée des secrets (HashiCorp Vault ou Sealed Secrets)
# Ceci est un exemple démontrant l'approche GitOps pour éviter de stocker
# des mots de passe en clair dans Git.
#
# Processus de mise en place (utile pour ta démonstration de PFE) :
# 1. L'installation du contrôleur Bitnami Sealed Secrets sur le cluster.
# 2. La création d'un secret localement :
#    echo -n "P@ssw0rdSup3rS3cure!" | kubectl create secret generic db-pass --dry-run=client --from-file=password=/dev/stdin -o json > secret.json
# 3. Le chiffrement via kubeseal (qui génère un yaml comme ci-dessous) :
#    kubeseal -f secret.json -w kubernetes/sealed-secret-demo.yaml
# 4. Git Push ! Checkov et Trivy ne trouveront pas de fuite de mot de passe car il est chiffré.
#
# Une fois déployé avec 'kubectl apply', le contrôleur Sealed Secrets de K8s reconstituera
# le véritable secret Opaque utilisable par tes pods.

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-db-pass
  namespace: prod
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Hash asymétrique (qui ne peut être déchiffré QUE par le cluster où SealedSecrets est installé)
    password: AgBy3i4OJSWK+PiTySYZZA9vkA+vX/fQx5y27oP... # (Ceci est un exemple)
  template:
    metadata:
      name: demo-db-pass
      labels:
        app: devsecops-app
    type: Opaque
